# Describes the format for available component services

whitelist_add:
  fields:
    mac_address:
      required: true
      example: "11:22:33:AA:BB:CC"
      selector:
        text:

blacklist_add:
  fields:
    mac_address:
      required: true
      example: "11:22:33:AA:BB:CC"
      selector:
        text:

whitelist_remove:
  fields:
    mac_address:
      required: true
      example: "11:22:33:AA:BB:CC"
      selector:
        text:

blacklist_remove:
  fields:
    mac_address:
      required: true
      example: "11:22:33:AA:BB:CC"
      selector:
        text:

guest_network_setup:
  fields:
    serial_number:
      required: true
      selector:
        text:
    enabled:
      required: true
      example: true
      default: true
      selector:
        boolean:
    ssid:
      required: true
      example: "MyGuestWiFi"
      selector:
        text:
    duration:
      required: true
      example: "four_hours"
      default: "four_hours"
      selector:
        select:
          translation_key: "wifi_duration"
          options:
            - "four_hours"
            - "one_day"
            - "unlimited"
    security:
      required: true
      example: "encrypted"
      default: "encrypted"
      selector:
        select:
          translation_key: "wifi_security"
          options:
            - "encrypted"
            - "open"
    password:
      required: true
      example: "K3k*eJWtFv!~ME4}"
      selector:
        text:

port_mapping_add:
  fields:
    internal_host:
      required: true
      example: "192.168.3.50"
      selector:
        text:
    internal_port:
      required: true
      example: 8080
      selector:
        number:
    external_port:
      required: true
      example: 18080
      selector:
        number:
    protocol:
      required: true
      example: "TCP"
      default: "TCP"
      selector:
        select:
          options:
            - "TCP"
            - "UDP"
    description:
      required: false
      example: "My service"
      selector:
        text:
    enabled:
      required: false
      example: true
      default: true
      selector:
        boolean:

port_mapping_remove:
  fields:
    external_port:
      required: true
      example: 18080
      selector:
        number:
    protocol:
      required: true
      example: "TCP"
      default: "TCP"
      selector:
        select:
          options:
            - "TCP"
            - "UDP"

port_mapping_list:
  description: "List all current port forwarding mappings."